### ISSUE TITLE
Longer-ish scenario names cause annotated pass/fail results to be cut off

### ISSUE THREAD

**Issue by jondkinney** [hybridgroup/gitnesse#23] opened 2013-10-09 15:17 UTC
![screen shot 2013-10-09 at 10 16 11 am](https://f.cloud.github.com/assets/4521/1298632/e6356866-30f5-11e3-9d5a-d4cfb5834fb5.png)

Seems like the formatting could be improved here. Maybe made multi-line?

**Comment by stewart** [comment] 2013-10-09 16:18
I'm not sure how the multi-line formatting would work. Maybe the scenario names could be truncated with an ellipsis to fit on a single line?

**Comment by jondkinney** [comment] 2013-10-09 18:52
It seems like there are some common things that could be extracted maybe? For instance, from what I can tell, only the last result is shown/annotated, so repeating that might be unnecessary. Same with the machine name and date/time. The file is run fully, so having that per scenario it just noisy. Maybe something like this?

```
Last Result For Feature: Creating a new company
Run at: 10/9/2013 - 10:09 AM
Run on: Jon's Work Laptop

Scenarios: 
---------------
`passing` 'prompting for creation of a new company before starting the first campaign'
`passing` 'creating a new company'
`passing` 'edit company'
```

And so on

Perhaps even repeating the `passing` is unnecessary. Maybe breaking it up into Passing Scenarios: and Failing Scenarios: would be better? Of course, would anyone ever push a failing scenario? Does that even work? If not, the 'passing' is even more redundant to include next to each story.

**Comment by stewart** [comment] 2013-10-09 18:56
The problem is, right now our hooks get called after every scenario and I'm not sure if there's a way to get the results of every feature/scenario after Cucumber has finished running. I am investigating alternative, less repetitive formatting, though.

**Comment by stewart** [comment] 2013-10-09 19:29
Tinkering right now, how does a format like this strike you?

![](http://i.imgur.com/NWHuchm.png)

**Comment by jondkinney** [comment] 2013-10-09 19:36
That's certainly more readable, if a little verbose.

What about putting the passing/failing in place of the scenario title? Probably safe to say we know it's a scenario already, and whether it passed or failed is the most important thing to know.

Personally I'd also unify the verbiage of the metadata to say either Last Run At: and Last Run On: or just Run At: and Run On:

Maybe tighten up the spacing between the scenario title and the bullets, but that's just being picky :p 

Thanks for entertaining some iteration on the formatting though! Definitely an improvement.

**Comment by stewart** [comment] 2013-10-09 20:13
Having everything be a bullet point was causing some formatting issues with the wiki css, so separating scenarios with horizontal rules:

![](http://i.imgur.com/4KOTNaT.png)

**Comment by jondkinney** [comment] 2013-10-09 21:05
It'd be awesome to be able to get things to 2 lines if possible. Maybe:

`passing` Features already exist in local, but not remote wiki
- **Run At:** Oct 09, 2013, 1:07 PM  &nbsp;&bull;&nbsp;  **Run On:** Andrew Stweart's MacBook

---

`passing` Features already exist in local, but not remote wiki
- **Run At:** Oct 09, 2013, 1:07 PM  &nbsp;&bull;&nbsp;  **Run On:** Andrew Stweart's MacBook

**Comment by stewart** [comment] 2013-10-09 21:25
How's this?

![screen shot 2013-10-09 at 2 24 31 pm](https://f.cloud.github.com/assets/489142/1301858/3c71e2e4-3129-11e3-9339-f7fe47707475.png)

**Comment by jondkinney** [comment] 2013-10-09 21:54
Nice! It might look slick to bold the feature name too? I think that would make it a little easier to visually parse at a glance.

**Comment by stewart** [comment] 2013-10-10 00:11
I really like this version:

![](http://i.imgur.com/JQidE33.png)

If that satisfies you, I'll close this issue.

**Comment by jondkinney** [comment] 2013-10-10 00:37
@stewart looks great! Thanks for taking the time to tweak on it with me :)

**Comment by stewart** [comment] 2013-10-10 00:38
Awesome, thanks for bringing it up. This will hopefully get merged in and pushed as a release by the end of the week.

**Closed as completed by stewart** 2013-10-10 00:38 UTC
